import type { ProtocolDefinition } from "./types";

export const PROTOCOLS: ProtocolDefinition[] = [
  {
    id: "aave-v3",
    name: "Aave V3",
    chain: "ethereum",
    website: "https://aave.com",
    description: "Decentralized lending and borrowing protocol. Users deposit assets to earn yield, borrowers take overcollateralized loans.",
    tvl: "$12.4B",
    contracts: [
      {
        name: "Pool (Proxy)",
        address: "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2",
        description: "Main lending pool. All user deposits and borrows go through this contract. Holds the core lending logic via upgradeable proxy.",
        impacts: ["user-funds"],
        holdsUserFunds: true,
        holdsTreasury: false,
      },
      {
        name: "PoolConfigurator (Proxy)",
        address: "0x64b761D848206f447Fe2dd461b0c635Ec39EbB27",
        description: "Configures pool parameters: reserve factors, liquidation thresholds, interest rate models. Can freeze/unfreeze markets.",
        impacts: ["user-funds", "protocol-halt"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
      {
        name: "ACLManager",
        address: "0xc2aaCf6553D20d1e9166F9169e23631E4F15fD38",
        description: "Access control list. Manages who has POOL_ADMIN, EMERGENCY_ADMIN, RISK_ADMIN, ASSET_LISTING_ADMIN roles.",
        impacts: ["governance"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
      {
        name: "PoolAddressesProvider",
        address: "0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e",
        description: "Registry that points to all pool components. Can change which implementation the Pool proxy uses. The master key.",
        impacts: ["user-funds", "treasury", "governance"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
      {
        name: "Treasury Controller",
        address: "0x3d569673dAa0575c936c7c67c4E6AedA69CC630C",
        description: "Controls the Aave protocol treasury. Can transfer collected protocol fees.",
        impacts: ["treasury", "fee-extraction"],
        holdsUserFunds: false,
        holdsTreasury: true,
      },
      {
        name: "Aave Governance V3 Executor",
        address: "0x5300A1a15135EA4dc7aD5a167152C01EFc9b192A",
        description: "Timelock executor for governance proposals. All major changes go through governance vote + delay.",
        impacts: ["governance"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
    ],
  },
  {
    id: "uniswap-v3",
    name: "Uniswap V3",
    chain: "ethereum",
    website: "https://uniswap.org",
    description: "Concentrated liquidity AMM. LPs provide liquidity in price ranges, traders swap tokens.",
    tvl: "$5.2B",
    contracts: [
      {
        name: "UniswapV3Factory",
        address: "0x1F98431c8aD98523631AE4a59f267346ea31F984",
        description: "Deploys new liquidity pools. Owner can enable new fee tiers and set protocol fee switch. Immutable after deployment.",
        impacts: ["fee-extraction"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
      {
        name: "SwapRouter02",
        address: "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45",
        description: "Routes swaps through optimal paths. Stateless — does not hold funds. Immutable.",
        impacts: ["none"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
      {
        name: "NonfungiblePositionManager",
        address: "0xC36442b4a4522E871399CD717aBDD847Ab11FE88",
        description: "Manages LP positions as NFTs. Users deposit liquidity through this contract. Immutable.",
        impacts: ["user-funds"],
        holdsUserFunds: true,
        holdsTreasury: false,
      },
      {
        name: "Governance Timelock",
        address: "0x1a9C8182C09F50C8318d769245beA52c32BE35BC",
        description: "Timelock for governance actions. Controls protocol fee switch on factory. 2-day minimum delay.",
        impacts: ["governance", "fee-extraction"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
      {
        name: "UNI Token",
        address: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
        description: "Governance token. Holders vote on protocol changes. Fixed supply, no mint function.",
        impacts: ["none"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
    ],
  },
  {
    id: "lido",
    name: "Lido",
    chain: "ethereum",
    website: "https://lido.fi",
    description: "Liquid staking protocol. Users deposit ETH and receive stETH, which accrues staking rewards.",
    tvl: "$25.8B",
    contracts: [
      {
        name: "Lido (stETH Proxy)",
        address: "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84",
        description: "Main staking contract. Holds all staked ETH. Issues stETH. Upgradeable proxy — the most critical contract in DeFi by TVL.",
        impacts: ["user-funds", "token-logic"],
        holdsUserFunds: true,
        holdsTreasury: false,
      },
      {
        name: "Node Operators Registry",
        address: "0x55032650b14df07b85bF18A3a3eC8E0Af2e028d5",
        description: "Manages approved node operators who run validators. Can add/remove operators, change staking limits.",
        impacts: ["user-funds"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
      {
        name: "Withdrawal Queue",
        address: "0x889edC2eDab5f40e902b864aD4d7AdE8E412F9B1",
        description: "Manages stETH → ETH withdrawal requests. Upgradeable proxy.",
        impacts: ["user-funds", "protocol-halt"],
        holdsUserFunds: true,
        holdsTreasury: false,
      },
      {
        name: "Lido DAO Voting (Aragon)",
        address: "0x2e59A20f205bB85a89C53f1936454680651E618e",
        description: "DAO governance. Controls upgrades to Lido contracts, node operator management, fee distribution.",
        impacts: ["governance"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
      {
        name: "Lido Treasury",
        address: "0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c",
        description: "Holds protocol fees and DAO treasury funds.",
        impacts: ["treasury"],
        holdsUserFunds: false,
        holdsTreasury: true,
      },
      {
        name: "Gate Seal",
        address: "0x1aD5CB2955940f998081c1Ef5F5f00875431cb6C",
        description: "Emergency pause committee. Can pause withdrawals and staking for a limited time. One-time use.",
        impacts: ["protocol-halt"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
    ],
  },
  {
    id: "maker",
    name: "MakerDAO / Sky",
    chain: "ethereum",
    website: "https://makerdao.com",
    description: "CDP-based stablecoin protocol. Users lock collateral to mint DAI. Governance controls risk parameters.",
    tvl: "$8.1B",
    contracts: [
      {
        name: "Vat (Core Engine)",
        address: "0x35D1b3F3D7966A1DFe207aa4514C12a259A0492B",
        description: "Core accounting engine. Tracks all collateral positions (CDPs) and DAI debt. Immutable — no proxy.",
        impacts: ["user-funds"],
        holdsUserFunds: true,
        holdsTreasury: false,
      },
      {
        name: "DSPause (Governance Timelock)",
        address: "0xbE286431454714F511008713973d3B053A2d38f3",
        description: "Governance timelock. All parameter changes go through governance vote + delay. Controls the entire system.",
        impacts: ["governance", "user-funds", "token-logic"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
      {
        name: "MCD_DAI (DAI Token)",
        address: "0x6B175474E89094C44Da98b954EedeAC495271d0F",
        description: "DAI stablecoin. Authorized minters are controlled by governance. If minting auth is compromised, infinite DAI can be created.",
        impacts: ["token-logic"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
      {
        name: "MCD_SPOT (Price Oracle Module)",
        address: "0x65C79fcB50Ca1594B025960e539eD7A9a6D434A3",
        description: "Feeds collateral prices to the system. If manipulated, can trigger mass liquidations or allow undercollateralized minting.",
        impacts: ["user-funds", "oracle"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
      {
        name: "MCD_END (Emergency Shutdown)",
        address: "0x0e2e8F1D1326A4B9633D96222Ce399c708B19c28",
        description: "Global settlement module. Can shut down the entire Maker system. Users can redeem collateral. Nuclear option.",
        impacts: ["protocol-halt", "user-funds"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
      {
        name: "MCD_ESM (Emergency Shutdown Trigger)",
        address: "0x09e05fF6142F2f9de8B6B65855A1d56B6cfE4c58",
        description: "Burns 150K MKR to trigger emergency shutdown. Permissionless — anyone with enough MKR can trigger it.",
        impacts: ["protocol-halt"],
        holdsUserFunds: false,
        holdsTreasury: false,
      },
    ],
  },
];

export function getProtocolById(id: string): ProtocolDefinition | undefined {
  return PROTOCOLS.find((p) => p.id === id);
}
